<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="TradePilot.Application.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradePilot.Domain\TradePilot.Domain.csproj" />
    <ProjectReference Include="..\TradePilot.Indicators\TradePilot.Indicators.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
  </ItemGroup>

</Project>
