<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>f1e65898-3404-42c8-852d-f1ecf27f92b3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingApp.AI\TradingApp.AI.csproj" />
    <ProjectReference Include="..\TradingApp.Application\TradingApp.Application.csproj" />
    <ProjectReference Include="..\TradingApp.Infrastructure\TradingApp.Infrastructure.csproj" />
    <ProjectReference Include="..\TradingApp.Persistence\TradingApp.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.25.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.0.0" />
  </ItemGroup>

</Project>
