<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TradingApp.Worker-db0632c8-0882-4121-b1a9-e1d6aa94d7d1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingApp.Application\TradingApp.Application.csproj" />
    <ProjectReference Include="..\TradingApp.Infrastructure\TradingApp.Infrastructure.csproj" />
    <ProjectReference Include="..\TradingApp.Persistence\TradingApp.Persistence.csproj" />
  </ItemGroup>
</Project>
