<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="TradePilot.Infrastructure.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradePilot.Application\TradePilot.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.25.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.83.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageReference Include="Nethereum.ABI" Version="6.0.4" />
    <PackageReference Include="Nethereum.Signer" Version="6.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

</Project>
