// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingApp.Persistence;

#nullable disable

namespace TradingApp.Persistence.Migrations
{
    [DbContext(typeof(TradingAppDbContext))]
    [Migration("20260328190000_AddBacktestRunStatus")]
    partial class AddBacktestRunStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("TradingApp.Domain.Entities.BacktestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageHoldTimeMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageTradePnl")
                        .HasColumnType("REAL");

                    b.Property<int>("CandlesReplayed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("HedgesOpened")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InitialCapital")
                        .HasColumnType("REAL");

                    b.Property<string>("IntervalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("REAL");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrategyConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCandles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalFeesPaid")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPnl")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TradesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WinRate")
                        .HasColumnType("REAL");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.Candle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Close")
                        .HasColumnType("REAL");

                    b.Property<double>("High")
                        .HasColumnType("REAL");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Low")
                        .HasColumnType("REAL");

                    b.Property<int>("NumTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Open")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Hyperliquid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Symbol", "Interval", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_Candles_Source_Symbol_Interval_Timestamp");

                    b.ToTable("Candles", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.FundingRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarkPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_FundingRates_Symbol_Timestamp");

                    b.ToTable("FundingRates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
