// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingApp.Persistence;

#nullable disable

namespace TradingApp.Persistence.Migrations
{
    [DbContext(typeof(TradingAppDbContext))]
    [Migration("20260407205348_AddLlmContextSnapshots")]
    partial class AddLlmContextSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("TradingApp.Domain.Entities.BacktestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AuditLogEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageHoldTimeMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageTradePnl")
                        .HasColumnType("REAL");

                    b.Property<string>("CandleLogJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CandlesReplayed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquityTimeSeriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GridCycleLogJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("HedgesOpened")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InitialCapital")
                        .HasColumnType("REAL");

                    b.Property<string>("IntervalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("REAL");

                    b.Property<string>("OrderEventLogJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrategyConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StrategyRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCandles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalFeesPaid")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPnl")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TradesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WinRate")
                        .HasColumnType("REAL");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("IX_BacktestRuns_StrategyId");

                    b.ToTable("BacktestRuns", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.Candle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Close")
                        .HasColumnType("REAL");

                    b.Property<double>("High")
                        .HasColumnType("REAL");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Low")
                        .HasColumnType("REAL");

                    b.Property<int>("NumTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Open")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Hyperliquid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Symbol", "Interval", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_Candles_Source_Symbol_Interval_Timestamp");

                    b.ToTable("Candles", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.FundingRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarkPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_FundingRates_Symbol_Timestamp");

                    b.ToTable("FundingRates", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.GridCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AnchorPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilledLevels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GridCycleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RealisedPnl")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLevels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GridCycleId")
                        .IsUnique()
                        .HasDatabaseName("IX_GridCycles_GridCycleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_GridCycles_UserId");

                    b.HasIndex("StrategyName", "Symbol", "Lifecycle")
                        .HasDatabaseName("IX_GridCycles_Strategy_Symbol_Lifecycle");

                    b.ToTable("GridCycles", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.LiveFill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("ClosedPnl")
                        .HasColumnType("REAL");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Fee")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FilledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_LiveFills_OrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LiveFills_UserId");

                    b.HasIndex("Symbol", "FilledAtUtc")
                        .HasDatabaseName("IX_LiveFills_Symbol_FilledAtUtc");

                    b.ToTable("LiveFills", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.LiveOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GridCycleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GridCycleId")
                        .HasDatabaseName("IX_LiveOrders_GridCycleId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_LiveOrders_OrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LiveOrders_UserId");

                    b.ToTable("LiveOrders", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.LlmContextSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("DerivedRegime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventRisk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("GeneratedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacroRegime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketSentiment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAtUtc")
                        .HasDatabaseName("IX_LlmContextSnapshots_GeneratedAtUtc");

                    b.HasIndex("Symbol", "GeneratedAtUtc")
                        .HasDatabaseName("IX_LlmContextSnapshots_Symbol_GeneratedAtUtc");

                    b.ToTable("LlmContextSnapshots", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.MacroEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Actual")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlockStartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPostBlockMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPreBlockMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Forecast")
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Previous")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayloadJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReleasedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Revised")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScheduledAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockEndUtc")
                        .HasDatabaseName("IX_MacroEvents_BlockEndUtc");

                    b.HasIndex("BlockStartUtc")
                        .HasDatabaseName("IX_MacroEvents_BlockStartUtc");

                    b.HasIndex("Importance")
                        .HasDatabaseName("IX_MacroEvents_Importance");

                    b.HasIndex("ScheduledAtUtc")
                        .HasDatabaseName("IX_MacroEvents_ScheduledAtUtc");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("IX_MacroEvents_Provider_ProviderEventId");

                    b.ToTable("MacroEvents", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.MacroSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsFetched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsInserted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_MacroSyncRuns_StartedAtUtc");

                    b.ToTable("MacroSyncRuns", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.OptimizationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageHoldTimeMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageTradePnl")
                        .HasColumnType("REAL");

                    b.Property<double?>("CalmarRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("FitnessScore")
                        .HasColumnType("REAL");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("REAL");

                    b.Property<double?>("OosFitnessScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("OosMaxDrawdown")
                        .HasColumnType("REAL");

                    b.Property<double?>("OosTotalPnl")
                        .HasColumnType("REAL");

                    b.Property<int?>("OosTotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OosWinRate")
                        .HasColumnType("REAL");

                    b.Property<Guid>("OptimizationRunId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProfitFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SharpeRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("SignalDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SortinoRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("StrategyConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalFeesPaid")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPnl")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WinRate")
                        .HasColumnType("REAL");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OptimizationRunId")
                        .HasDatabaseName("IX_OptimizationResults_RunId");

                    b.HasIndex("OptimizationRunId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("IX_OptimizationResults_RunId_Rank");

                    b.ToTable("OptimizationResults", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.OptimizationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InitialCapital")
                        .HasColumnType("REAL");

                    b.Property<int>("QualifiedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SweepConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThresholdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCombinations")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_OptimizationRuns_CreatedAtUtc");

                    b.ToTable("OptimizationRuns", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_Strategies_UserId_IsActive");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Strategies_UserId_Name")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Strategies", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.StrategyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFallback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_StrategyReviews_StrategyId_RevisionNumber");

                    b.ToTable("StrategyReviews", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.StrategyRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_StrategyRevisions_StrategyId_RevisionNumber");

                    b.ToTable("StrategyRevisions", (string)null);
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.OptimizationResult", b =>
                {
                    b.HasOne("TradingApp.Domain.Entities.OptimizationRun", null)
                        .WithMany()
                        .HasForeignKey("OptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.StrategyReview", b =>
                {
                    b.HasOne("TradingApp.Domain.Entities.Strategy", null)
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingApp.Domain.Entities.StrategyRevision", b =>
                {
                    b.HasOne("TradingApp.Domain.Entities.Strategy", null)
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
