// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingApp.Persistence;

#nullable disable

namespace TradingApp.Persistence.Migrations
{
    [DbContext(typeof(TradingAppDbContext))]
    partial class TradingAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("TradingApp.Domain.Entities.Candle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Close")
                        .HasColumnType("REAL");

                    b.Property<double>("High")
                        .HasColumnType("REAL");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Low")
                        .HasColumnType("REAL");

                    b.Property<int>("NumTrades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Open")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Interval", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_Candles_Symbol_Interval_Timestamp");

                    b.ToTable("Candles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
