using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using TradingApp.Application.Abstractions.Services;
using TradingApp.Application.Agent.Models;
using TradingApp.Application.MarketData.Models;

namespace TradingApp.Worker.Services;

/// <summary>
/// SignalR publisher that relays events to the API's /api/agent/relay endpoint
/// via HTTP. Used when the Worker doesn't have an Azure SignalR connection
/// (local development). The API then broadcasts to connected SignalR clients.
/// </summary>
public sealed class RelaySignalRPublisher : ISignalRPublisher
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<RelaySignalRPublisher> _logger;

    public RelaySignalRPublisher(
        IHttpClientFactory httpClientFactory,
        ILogger<RelaySignalRPublisher> logger)
    {
        _httpClientFactory = httpClientFactory;
        _logger = logger;
    }

    public Task BroadcastFillEventAsync(FillEventDto fill, CancellationToken cancellationToken = default)
        => RelayAsync(new SignalRRelayEnvelope { Fill = fill }, cancellationToken);

    public Task BroadcastOrderUpdateAsync(OrderUpdateDto orderUpdate, CancellationToken cancellationToken = default)
        => RelayAsync(new SignalRRelayEnvelope { OrderUpdate = orderUpdate }, cancellationToken);

    public Task BroadcastUserConnectionStatusAsync(ConnectionStatusDto status, CancellationToken cancellationToken = default)
        => RelayAsync(new SignalRRelayEnvelope { UserConnectionStatus = status }, cancellationToken);

    // These events are not generated by the Worker — no-op
    public Task BroadcastPriceUpdateAsync(PriceUpdateDto update, CancellationToken cancellationToken = default)
        => Task.CompletedTask;

    public Task BroadcastConnectionStatusAsync(ConnectionStatusDto status, CancellationToken cancellationToken = default)
        => Task.CompletedTask;

    public Task BroadcastOrdersResyncAsync(IReadOnlyList<OpenOrderDto> orders, CancellationToken cancellationToken = default)
        => Task.CompletedTask;

    public Task BroadcastPositionsResyncAsync(IReadOnlyList<PositionDto> positions, CancellationToken cancellationToken = default)
        => Task.CompletedTask;

    public Task BroadcastExecutionLogAsync(ExecutionLogDto log, CancellationToken cancellationToken = default)
        => Task.CompletedTask; // Execution logs already relayed via heartbeat

    private async Task RelayAsync(SignalRRelayEnvelope envelope, CancellationToken cancellationToken)
    {
        try
        {
            using var client = _httpClientFactory.CreateClient(AgentCheckInService.HttpClientName);
            var response = await client.PostAsJsonAsync("/api/agent/relay", envelope, JsonOptions, cancellationToken);
            response.EnsureSuccessStatusCode();
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to relay SignalR event to API — UI notification may be missed");
        }
    }
}
